#!/bin/sh
# aoa-sdk checkpoint pre-merge-commit hook v1
# GENERATED by 8Dionysus/scripts/manage_workspace_git_hooks.py; edit config/git_hooks/pre-merge-commit.sh first.

repo_root="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
workspace_root="${AOA_CHECKPOINT_WORKSPACE_ROOT:-<workspace-root>}"
aoa_bin="${AOA_CHECKPOINT_AOA_BIN:-aoa}"

output="$("$aoa_bin" checkpoint git-boundary-check "$repo_root" --boundary merge --root "$workspace_root" 2>&1)"
status=$?

if [ -n "$output" ]; then
  printf '%s\n' "$output"
fi

exit "$status"
