from __future__ import annotations

import json
import stat
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "scripts"))

from manage_workspace_git_hooks import (  # noqa: E402
    HOOK_MODE,
    build_hook_plans,
    render_hook_template,
    workspace_git_hooks_report,
)


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def init_repo(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)
    subprocess.run(["git", "-C", path.as_posix(), "init", "-q"], check=True)


class WorkspaceGitHooksTests(unittest.TestCase):
    def test_hook_template_renders_workspace_root(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            template = Path(temp_dir) / "hook.sh"
            write_text(template, "root=<workspace-root>\n")

            rendered = render_hook_template(template, Path("/srv/AbyssOS"))

            self.assertEqual(rendered, "root=/srv/AbyssOS\n")

    def test_dry_run_reports_missing_hooks(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            temp_root = Path(temp_dir)
            owner_root = temp_root / "8Dionysus"
            workspace_root = temp_root / "workspace"
            self._make_templates(owner_root)
            init_repo(workspace_root / "aoa-sdk")

            report = workspace_git_hooks_report(owner_root, workspace_root)

            self.assertTrue(report["changed"])
            self.assertFalse(report["blocked"])
            self.assertEqual(report["repository_count"], 1)
            self.assertEqual(report["operation_count"], 3)
            self.assertEqual(report["managed_hooks"], ["pre-merge-commit", "pre-push", "post-commit"])
            self.assertEqual({operation["reason"] for operation in report["operations"]}, {"missing_hook"})
            json.dumps(report)

    def test_execute_installs_source_owned_hooks(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            temp_root = Path(temp_dir)
            owner_root = temp_root / "8Dionysus"
            workspace_root = temp_root / "workspace"
            self._make_templates(owner_root)
            repo_root = workspace_root / "aoa-sdk"
            init_repo(repo_root)

            report = workspace_git_hooks_report(owner_root, workspace_root, execute=True)

            self.assertTrue(report["changed"])
            hooks_dir = repo_root / ".git" / "hooks"
            expected = build_hook_plans(owner_root, workspace_root)
            for plan in expected:
                hook_path = hooks_dir / plan.hook_name
                self.assertEqual(hook_path.read_text(encoding="utf-8"), plan.rendered_text)
                self.assertEqual(stat.S_IMODE(hook_path.stat().st_mode), HOOK_MODE)

            clean = workspace_git_hooks_report(owner_root, workspace_root)
            self.assertFalse(clean["changed"])
            self.assertFalse(clean["blocked"])

    def test_unmanaged_existing_hook_blocks_without_force(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            temp_root = Path(temp_dir)
            owner_root = temp_root / "8Dionysus"
            workspace_root = temp_root / "workspace"
            self._make_templates(owner_root)
            repo_root = workspace_root / "aoa-sdk"
            init_repo(repo_root)
            unmanaged = repo_root / ".git" / "hooks" / "pre-push"
            unmanaged.write_text("#!/bin/sh\necho custom\n", encoding="utf-8")
            unmanaged.chmod(0o755)

            report = workspace_git_hooks_report(owner_root, workspace_root)

            blocked = [operation for operation in report["operations"] if operation["action"] == "blocked"]
            self.assertTrue(report["blocked"])
            self.assertEqual(len(blocked), 1)
            self.assertEqual(blocked[0]["reason"], "unmanaged_existing_hook")
            self.assertEqual(unmanaged.read_text(encoding="utf-8"), "#!/bin/sh\necho custom\n")

    def test_force_replaces_unmanaged_existing_hook(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            temp_root = Path(temp_dir)
            owner_root = temp_root / "8Dionysus"
            workspace_root = temp_root / "workspace"
            self._make_templates(owner_root)
            repo_root = workspace_root / "aoa-sdk"
            init_repo(repo_root)
            unmanaged = repo_root / ".git" / "hooks" / "pre-push"
            unmanaged.write_text("#!/bin/sh\necho custom\n", encoding="utf-8")

            report = workspace_git_hooks_report(owner_root, workspace_root, execute=True, force=True)

            self.assertFalse(report["blocked"])
            self.assertIn("GENERATED by 8Dionysus", unmanaged.read_text(encoding="utf-8"))

    def test_non_regular_existing_hook_blocks_even_with_force(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            temp_root = Path(temp_dir)
            owner_root = temp_root / "8Dionysus"
            workspace_root = temp_root / "workspace"
            self._make_templates(owner_root)
            repo_root = workspace_root / "aoa-sdk"
            init_repo(repo_root)
            (repo_root / ".git" / "hooks" / "pre-push").mkdir(parents=True)

            report = workspace_git_hooks_report(owner_root, workspace_root, execute=True, force=True)

            blocked = [operation for operation in report["operations"] if operation["action"] == "blocked"]
            self.assertTrue(report["blocked"])
            self.assertEqual(len(blocked), 1)
            self.assertEqual(blocked[0]["reason"], "existing_hook_is_not_regular_file")

    def _make_templates(self, owner_root: Path) -> None:
        for hook_name in ("pre-merge-commit", "pre-push", "post-commit"):
            write_text(
                owner_root / "config" / "git_hooks" / f"{hook_name}.sh",
                (
                    "#!/bin/sh\n"
                    f"# aoa-sdk checkpoint {hook_name} hook test\n"
                    "# GENERATED by 8Dionysus/scripts/manage_workspace_git_hooks.py; edit config/git_hooks first.\n"
                    "workspace_root=\"${AOA_CHECKPOINT_WORKSPACE_ROOT:-<workspace-root>}\"\n"
                    "printf '%s\\n' \"$workspace_root\"\n"
                ),
            )


if __name__ == "__main__":
    unittest.main()
