#!/usr/bin/env python3
"""Install and validate AoA-managed repo-local Git hooks.

Git keeps active hooks inside each checkout's private Git directory, so these
files cannot be projected like ordinary shared-root install surfaces. This
helper makes that local state source-owned, checkable, and safely reinstallable
from 8Dionysus templates.
"""
from __future__ import annotations

import argparse
import json
import stat
import subprocess
from dataclasses import dataclass
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
WORKSPACE_ROOT_PLACEHOLDER = "<workspace-root>"
HOOK_MODE = 0o755
MANAGED_MARKERS = (
    "# aoa-sdk checkpoint ",
    "# GENERATED by 8Dionysus/scripts/manage_workspace_git_hooks.py",
)
HOOK_TEMPLATES: tuple[tuple[str, str], ...] = (
    ("pre-merge-commit", "pre-merge-commit.sh"),
    ("pre-push", "pre-push.sh"),
    ("post-commit", "post-commit.sh"),
)


@dataclass(frozen=True)
class HookPlan:
    hook_name: str
    template_path: Path
    rendered_text: str


@dataclass
class Operation:
    action: str
    repo_root: Path
    hook_name: str
    hook_path: Path
    reason: str
    source_path: Path | None = None
    rendered_text: str | None = None
    file_mode: int = HOOK_MODE

    def to_summary(self, workspace_root: Path, owner_root: Path) -> dict[str, object]:
        payload: dict[str, object] = {
            "action": self.action,
            "repo": _display_path(self.repo_root, workspace_root),
            "hook": self.hook_name,
            "hook_path": _display_path(self.hook_path, workspace_root),
            "reason": self.reason,
        }
        if self.source_path is not None:
            payload["source_path"] = _display_path(self.source_path, owner_root)
        if self.action != "blocked":
            payload["file_mode"] = oct(self.file_mode)
        return payload


def render_hook_template(template_path: Path, workspace_root: Path) -> str:
    return template_path.read_text(encoding="utf-8").replace(
        WORKSPACE_ROOT_PLACEHOLDER,
        workspace_root.as_posix(),
    )


def build_hook_plans(owner_root: Path, workspace_root: Path) -> tuple[HookPlan, ...]:
    template_root = owner_root / "config" / "git_hooks"
    plans: list[HookPlan] = []
    for hook_name, template_name in HOOK_TEMPLATES:
        template_path = template_root / template_name
        if not template_path.is_file():
            raise FileNotFoundError(f"missing Git hook template: {template_path}")
        plans.append(
            HookPlan(
                hook_name=hook_name,
                template_path=template_path,
                rendered_text=render_hook_template(template_path, workspace_root),
            )
        )
    return tuple(plans)


def discover_workspace_git_repos(workspace_root: Path) -> tuple[Path, ...]:
    if not workspace_root.is_dir():
        raise FileNotFoundError(f"workspace root does not exist: {workspace_root}")
    repos = [
        child.resolve()
        for child in workspace_root.iterdir()
        if child.is_dir() and (child / ".git").exists()
    ]
    return tuple(sorted(repos, key=lambda path: path.name.lower()))


def resolve_selected_repos(workspace_root: Path, selections: tuple[str, ...]) -> tuple[Path, ...]:
    if not selections:
        return discover_workspace_git_repos(workspace_root)

    repos: list[Path] = []
    for selection in selections:
        raw_path = Path(selection).expanduser()
        repo_path = raw_path if raw_path.is_absolute() else workspace_root / selection
        repo_path = repo_path.resolve()
        if not repo_path.is_dir() or not (repo_path / ".git").exists():
            raise FileNotFoundError(f"selected repository is not a Git checkout: {selection}")
        repos.append(repo_path)
    return tuple(sorted(dict.fromkeys(repos), key=lambda path: path.name.lower()))


def workspace_git_hooks_report(
    owner_root: Path,
    workspace_root: Path,
    *,
    repo_selections: tuple[str, ...] = (),
    execute: bool = False,
    force: bool = False,
) -> dict[str, object]:
    owner_root = owner_root.resolve()
    workspace_root = workspace_root.resolve()
    hook_plans = build_hook_plans(owner_root, workspace_root)
    repo_roots = resolve_selected_repos(workspace_root, repo_selections)
    operations = _build_operations(repo_roots, hook_plans, force=force)
    blocked = [operation for operation in operations if operation.action == "blocked"]
    writable = [operation for operation in operations if operation.action != "blocked"]

    if execute and not blocked:
        for operation in writable:
            _apply_operation(operation)

    changed = bool(writable)
    blocked_any = bool(blocked)
    summary = [operation.to_summary(workspace_root, owner_root) for operation in operations]
    return {
        "owner_repo": "8Dionysus",
        "owner_root": owner_root.as_posix(),
        "workspace_root": workspace_root.as_posix(),
        "mode": "execute" if execute else "dry-run",
        "force": force,
        "changed": changed,
        "blocked": blocked_any,
        "repository_count": len(repo_roots),
        "repositories": [_display_path(repo, workspace_root) for repo in repo_roots],
        "managed_hooks": [plan.hook_name for plan in hook_plans],
        "source_templates": [
            _display_path(plan.template_path, owner_root) for plan in hook_plans
        ],
        "operation_count": len(summary),
        "blocked_count": len(blocked),
        "operations": summary,
        "next_step": _next_step(changed=changed, blocked=blocked_any, execute=execute),
    }


def _build_operations(
    repo_roots: tuple[Path, ...],
    hook_plans: tuple[HookPlan, ...],
    *,
    force: bool,
) -> list[Operation]:
    operations: list[Operation] = []
    for repo_root in repo_roots:
        hook_dir = resolve_git_hooks_dir(repo_root)
        for plan in hook_plans:
            hook_path = hook_dir / plan.hook_name
            operations.extend(_plan_hook(repo_root, hook_path, plan, force=force))
    return operations


def _plan_hook(repo_root: Path, hook_path: Path, plan: HookPlan, *, force: bool) -> list[Operation]:
    if _same_managed_hook(hook_path, plan.rendered_text):
        return []

    if hook_path.exists() or hook_path.is_symlink():
        if hook_path.exists() and not hook_path.is_symlink() and not hook_path.is_file():
            return [
                Operation(
                    action="blocked",
                    repo_root=repo_root,
                    hook_name=plan.hook_name,
                    hook_path=hook_path,
                    reason="existing_hook_is_not_regular_file",
                    source_path=plan.template_path,
                )
            ]
        if hook_path.is_symlink():
            if not force:
                return [
                    Operation(
                        action="blocked",
                        repo_root=repo_root,
                        hook_name=plan.hook_name,
                        hook_path=hook_path,
                        reason="existing_hook_is_not_regular_file",
                        source_path=plan.template_path,
                    )
                ]
        else:
            actual_text = hook_path.read_text(encoding="utf-8", errors="replace")
            if not _is_aoa_managed_hook(actual_text) and not force:
                return [
                    Operation(
                        action="blocked",
                        repo_root=repo_root,
                        hook_name=plan.hook_name,
                        hook_path=hook_path,
                        reason="unmanaged_existing_hook",
                        source_path=plan.template_path,
                    )
                ]

    return [
        Operation(
            action="write_hook",
            repo_root=repo_root,
            hook_name=plan.hook_name,
            hook_path=hook_path,
            reason=_hook_drift_reason(hook_path, plan.rendered_text),
            source_path=plan.template_path,
            rendered_text=plan.rendered_text,
        )
    ]


def resolve_git_hooks_dir(repo_root: Path) -> Path:
    result = subprocess.run(
        ["git", "-C", repo_root.as_posix(), "rev-parse", "--git-path", "hooks"],
        check=False,
        capture_output=True,
        text=True,
    )
    if result.returncode == 0:
        raw_text = result.stdout.strip()
        if raw_text:
            raw_path = Path(raw_text)
            return raw_path if raw_path.is_absolute() else repo_root / raw_path

    dot_git = repo_root / ".git"
    if dot_git.is_dir():
        return dot_git / "hooks"
    if dot_git.is_file():
        text = dot_git.read_text(encoding="utf-8", errors="replace").strip()
        prefix = "gitdir:"
        if text.lower().startswith(prefix):
            git_dir = Path(text[len(prefix) :].strip())
            if not git_dir.is_absolute():
                git_dir = repo_root / git_dir
            return git_dir.resolve() / "hooks"
    raise FileNotFoundError(f"cannot resolve Git hooks directory for {repo_root}")


def _same_managed_hook(hook_path: Path, expected_text: str) -> bool:
    if not hook_path.is_file() or hook_path.is_symlink():
        return False
    if hook_path.read_text(encoding="utf-8", errors="replace") != expected_text:
        return False
    return stat.S_IMODE(hook_path.stat().st_mode) == HOOK_MODE


def _is_aoa_managed_hook(text: str) -> bool:
    return any(marker in text for marker in MANAGED_MARKERS)


def _hook_drift_reason(hook_path: Path, expected_text: str) -> str:
    if not hook_path.exists() and not hook_path.is_symlink():
        return "missing_hook"
    if hook_path.is_file() and not hook_path.is_symlink():
        actual_mode = stat.S_IMODE(hook_path.stat().st_mode)
        if hook_path.read_text(encoding="utf-8", errors="replace") == expected_text:
            return f"mode_drift:{oct(actual_mode)}"
    return "content_or_type_drift"


def _apply_operation(operation: Operation) -> None:
    if operation.action != "write_hook":
        raise ValueError(f"cannot apply non-write operation: {operation.action}")
    if operation.rendered_text is None:
        raise ValueError("write_hook operation missing rendered_text")
    operation.hook_path.parent.mkdir(parents=True, exist_ok=True)
    if operation.hook_path.exists() or operation.hook_path.is_symlink():
        operation.hook_path.unlink()
    operation.hook_path.write_text(operation.rendered_text, encoding="utf-8")
    operation.hook_path.chmod(operation.file_mode)


def _display_path(path: Path, root: Path) -> str:
    try:
        return path.resolve().relative_to(root.resolve()).as_posix() or "."
    except ValueError:
        return path.as_posix()


def _next_step(*, changed: bool, blocked: bool, execute: bool) -> str:
    if blocked:
        return (
            "Review unmanaged local Git hooks before replacing them. Re-run with --force only after "
            "confirming those local hooks are safe to overwrite."
        )
    if changed and execute:
        return "Repo-local Git hooks were installed. Re-run with --check --json to verify drift is clean."
    if changed:
        return "Run again with --execute --json to install the source-owned AoA Git hooks."
    return "Repo-local Git hooks are already in sync with 8Dionysus source templates."


def _format_text_report(report: dict[str, object]) -> str:
    lines = [
        f"mode: {report['mode']}",
        f"workspace_root: {report['workspace_root']}",
        f"changed: {report['changed']}",
        f"blocked: {report['blocked']}",
        f"repository_count: {report['repository_count']}",
        f"operation_count: {report['operation_count']}",
    ]
    for operation in report["operations"]:
        lines.append(
            f"{operation['action']}: {operation['repo']} {operation['hook']} "
            f"[{operation['reason']}]"
        )
    lines.append(f"next_step: {report['next_step']}")
    return "\n".join(lines)


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--owner-root", type=Path, default=REPO_ROOT)
    parser.add_argument("--workspace-root", type=Path, default=REPO_ROOT.parent)
    parser.add_argument(
        "--repo",
        action="append",
        default=[],
        help="Limit to a workspace child repo name or an absolute repo path. May be repeated.",
    )
    parser.add_argument("--execute", action="store_true", help="Install hooks. Dry-run is the default.")
    parser.add_argument("--check", action="store_true", help="Exit nonzero when hook drift exists.")
    parser.add_argument(
        "--force",
        action="store_true",
        help="Replace unmanaged existing hooks after manual review.",
    )
    parser.add_argument("--json", action="store_true", help="Emit JSON instead of text.")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    if args.execute and args.check:
        raise SystemExit("--execute and --check cannot be used together")

    report = workspace_git_hooks_report(
        args.owner_root,
        args.workspace_root,
        repo_selections=tuple(args.repo),
        execute=args.execute,
        force=args.force,
    )

    if args.json:
        print(json.dumps(report, indent=2))
    else:
        print(_format_text_report(report))

    if report["blocked"]:
        return 2
    if args.check and report["changed"]:
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
