from __future__ import annotations

import argparse
import json
import shlex
from pathlib import Path
from typing import Any


def load_json_object(path: Path) -> dict[str, Any]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError(f"expected json object in {path}")
    return payload


def format_toml_value(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, list):
        return "[" + ", ".join(format_toml_value(item) for item in value) + "]"
    if isinstance(value, str):
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    raise TypeError(f"unsupported TOML value type: {type(value)!r}")


def repo_path(
    workspace_root: Path,
    manifest: dict[str, Any],
    repo_key: str,
    cwd_repo_rel: str = "",
) -> Path:
    repo_dir = manifest["repos"][repo_key]
    path = workspace_root / repo_dir
    if cwd_repo_rel:
        path = path / cwd_repo_rel
    return path


def render_config_toml(
    *,
    manifest: dict[str, Any],
    profile: dict[str, Any],
    workspace_root: Path,
    manifest_rel: str = "config/codex_plane/runtime_manifest.v1.json",
    profile_rel: str = "config/codex_plane/profiles/linux-python3.json",
) -> str:
    lines: list[str] = [
        (
            "# GENERATED by 8Dionysus/scripts/render_codex_plane.py from "
            f"{manifest_rel} and {profile_rel} for workspace_root={workspace_root.as_posix()}"
        ),
        "# Edit the manifest/profile and rerender. Do not hand-edit this file.",
        f"project_root_markers = {format_toml_value(manifest['project_root_markers'])}",
        "",
        "[features]",
        f"codex_hooks = {format_toml_value(manifest['features'].get('codex_hooks', True))}",
        "",
    ]
    agents = manifest["agents"]
    lines.extend(
        [
            "[agents]",
            f"max_threads = {agents['max_threads']}",
            f"max_depth = {agents['max_depth']}",
            f"job_max_runtime_seconds = {agents['job_max_runtime_seconds']}",
            "",
        ]
    )
    for role in agents["roles"]:
        lines.extend(
            [
                f"[agents.{role['name']}]",
                f"description = {format_toml_value(role['description'])}",
                f"config_file = {format_toml_value(role['config_file'])}",
                f"nickname_candidates = {format_toml_value(role['nickname_candidates'])}",
                "",
            ]
        )
    lines.append("# Keep these server names stable if skill↔MCP wiring depends on them:")
    for server in manifest["mcp_servers"]:
        lines.append(f"# - {server['name']}")
    lines.append("")
    for server in manifest["mcp_servers"]:
        cwd = repo_path(
            workspace_root,
            manifest,
            server["repo_key"],
            server.get("cwd_repo_rel", ""),
        )
        args = list(profile.get("python_prefix_args", [])) + [server["script_rel"]]
        lines.extend(
            [
                f"[mcp_servers.{server['name']}]",
                f"command = {format_toml_value(profile['python_command'])}",
                f"args = {format_toml_value(args)}",
                f"cwd = {format_toml_value(cwd.as_posix())}",
                "",
            ]
        )
    return "\n".join(lines).rstrip() + "\n"


def render_hook_command(script_path: Path, profile: dict[str, Any]) -> str:
    pieces = [profile["python_command"], *profile.get("python_prefix_args", []), script_path.as_posix()]
    return " ".join(shlex.quote(str(piece)) for piece in pieces)


def render_hooks_json(
    *,
    manifest: dict[str, Any],
    profile: dict[str, Any],
    workspace_root: Path,
) -> dict[str, Any]:
    payload: dict[str, Any] = {"hooks": {}}
    for event_name, entries in manifest["hooks"].items():
        rendered_entries: list[dict[str, Any]] = []
        for entry in entries:
            hook = {
                "type": "command",
                "command": render_hook_command(workspace_root / entry["script_rel"], profile),
                "statusMessage": entry["statusMessage"],
                "timeout": entry["timeout"],
            }
            rendered_entry: dict[str, Any] = {"hooks": [hook]}
            if "matcher" in entry:
                rendered_entry["matcher"] = entry["matcher"]
            rendered_entries.append(rendered_entry)
        payload["hooks"][event_name] = rendered_entries
    return payload


def render_paths_report(
    *,
    manifest: dict[str, Any],
    profile: dict[str, Any],
    workspace_root: Path,
) -> dict[str, Any]:
    return {
        "workspace_root": workspace_root.as_posix(),
        "workspace_marker": manifest["workspace_marker"],
        "python_command": profile["python_command"],
        "python_prefix_args": profile.get("python_prefix_args", []),
        "repos": {
            repo_key: (workspace_root / repo_dir).as_posix()
            for repo_key, repo_dir in manifest["repos"].items()
        },
        "mcp_servers": {
            server["name"]: {
                "cwd": repo_path(
                    workspace_root,
                    manifest,
                    server["repo_key"],
                    server.get("cwd_repo_rel", ""),
                ).as_posix(),
                "script_rel": server["script_rel"],
            }
            for server in manifest["mcp_servers"]
        },
        "hooks": {
            event_name: [{"script_rel": entry["script_rel"]} for entry in entries]
            for event_name, entries in manifest["hooks"].items()
        },
    }


def ensure_parent(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Render path-bound AoA Codex plane surfaces from a source-owned manifest."
    )
    parser.add_argument("--manifest", type=Path, required=True)
    parser.add_argument("--profile", type=Path, required=True)
    parser.add_argument("--workspace-root", type=Path, required=True)
    parser.add_argument("--dest-config", type=Path, required=True)
    parser.add_argument("--dest-hooks", type=Path, required=True)
    parser.add_argument("--dest-report", type=Path, default=None)
    parser.add_argument("--check", action="store_true")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    manifest = load_json_object(args.manifest)
    profile = load_json_object(args.profile)
    workspace_root = args.workspace_root.expanduser().resolve()
    config_text = render_config_toml(
        manifest=manifest,
        profile=profile,
        workspace_root=workspace_root,
        manifest_rel=args.manifest.as_posix(),
        profile_rel=args.profile.as_posix(),
    )
    hooks_text = json.dumps(
        render_hooks_json(manifest=manifest, profile=profile, workspace_root=workspace_root),
        ensure_ascii=False,
        indent=2,
    ) + "\n"
    report_text = json.dumps(
        render_paths_report(manifest=manifest, profile=profile, workspace_root=workspace_root),
        ensure_ascii=False,
        indent=2,
    ) + "\n"

    if args.check:
        current_config = args.dest_config.read_text(encoding="utf-8") if args.dest_config.exists() else None
        current_hooks = args.dest_hooks.read_text(encoding="utf-8") if args.dest_hooks.exists() else None
        current_report = args.dest_report.read_text(encoding="utf-8") if args.dest_report and args.dest_report.exists() else None
        return 0 if (
            current_config == config_text
            and current_hooks == hooks_text
            and (args.dest_report is None or current_report == report_text)
        ) else 1

    ensure_parent(args.dest_config)
    args.dest_config.write_text(config_text, encoding="utf-8")
    ensure_parent(args.dest_hooks)
    args.dest_hooks.write_text(hooks_text, encoding="utf-8")
    if args.dest_report is not None:
        ensure_parent(args.dest_report)
        args.dest_report.write_text(report_text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
